apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-app
  labels:
    app: service-registry-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry-app
  template:
    metadata:
      labels:
        app: service-registry-app
    spec:
      containers:
      - name: service-registry-app
        image: sunildevops1/service-registry:35
        ports:
          - containerPort: 8761
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-app-service
  labels:
    app: service-registry-app
spec:
  type: NodePort
  selector:
    app: service-registry-app
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
