apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-app
  labels:
    app: cart-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service-app
  template:
    metadata:
      labels:
        app: cart-service-app
    spec:
      containers:
      - name: cart-service-app
        image: sunildevops1/cart-service:29
        ports:
          - containerPort: 9060
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service-app-service
  labels:
    app: cart-service-app
spec:
  type: ClusterIP
  selector:
    app: cart-service-app
  ports:
  - protocol: TCP
    port: 9060
    targetPort: 9060
