apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-app
  labels:
    app: auth-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-app
  template:
    metadata:
      labels:
        app: auth-service-app
    spec:
      containers:
      - name: auth-service-app
        image: sunildevops1/auth-service:28
        ports:
          - containerPort: 9030
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-app-service
  labels:
    app: auth-service-app
spec:
  type: ClusterIP
  selector:
    app: auth-service-app
  ports:
  - protocol: TCP
    port: 9030
    targetPort: 9030
